---
- name: install apache
  hosts: all
  tasks:
    - name: Install latest version of Apache
      apt:
       name: apache2
       state: latest

      notify:
       - Start Apache

  handlers:
    - name: Start Apache
      service:
         name: apache2
         state: started
